# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1685a9adbc22b8865f5b1f656eaa238d195f8e844e976481fac5c1fb073602d4577d7af24b5a334aaab92b096265bd81111bc5e2fba52f647922e0800a0545a5

test:
  secret_key_base: 3686ffa853c220a9e08dbf594f81a5361d7edc97d0704c4033dad2c0fc5fa2938bb7f5d1280a03cd0d191ca42c4b04fb486b24140d581e931cb1bc75a7823b6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
